# Generated by Django 3.2.7 on 2021-09-09 00:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_rename_description_todo_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='timeCreated',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
