# Generated by Django 3.2.7 on 2021-09-09 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_auto_20210909_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='registeredInDatabase',
        ),
        migrations.AddField(
            model_name='todo',
            name='serialNumber',
            field=models.IntegerField(default=1234),
            preserve_default=False,
        ),
    ]
